# Generated by Django 5.0.1 on 2024-02-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=100)),
                ('RFID', models.CharField(max_length=100)),
                ('Quantidade', models.IntegerField()),
                ('DataRetirada', models.DateTimeField()),
            ],
            options={
                'db_table': 'Medicamento',
            },
        ),
    ]
