# Generated by Django 5.0.1 on 2024-04-04 22:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0002_remove_medicamento_dataretirada_medicamento_porta'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='DataCriacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
