# Generated by Django 5.0.1 on 2024-04-05 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='Senha',
        ),
    ]
