# Generated by Django 5.0.1 on 2024-04-05 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('medicamentos', '0003_medicamento_datacriacao'),
        ('pacientes', '0002_remove_paciente_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescricao',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Data', models.DateTimeField()),
                ('Medicamentos', models.ManyToManyField(to='medicamentos.medicamento')),
                ('Medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.userprofile')),
                ('Paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacientes.paciente')),
            ],
            options={
                'db_table': 'Prescricao',
            },
        ),
    ]
