# Generated by Django 5.0.1 on 2024-04-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescricoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescricao',
            name='Data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
