# Generated by Django 5.0.1 on 2024-04-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0003_medicamento_datacriacao'),
        ('prescricoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescricao',
            name='IdMedicamento',
        ),
        migrations.AddField(
            model_name='prescricao',
            name='Medicamentos',
            field=models.ManyToManyField(to='medicamentos.medicamento'),
        ),
    ]
