# Generated by Django 5.0.1 on 2024-04-05 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescricoes', '0002_remove_prescricao_idmedicamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescricao',
            name='Quantidade',
        ),
    ]
