# Generated by Django 5.0.1 on 2024-04-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescricoes', '0003_prescricao_ativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescricao',
            name='Id',
        ),
        migrations.AddField(
            model_name='prescricao',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
