# Generated by Django 5.0.1 on 2024-04-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescricoes', '0004_remove_prescricao_id_prescricao_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescricao',
            name='id',
        ),
        migrations.AddField(
            model_name='prescricao',
            name='Id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
