# Generated by Django 5.0.1 on 2024-04-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescricoes', '0006_remove_prescricao_id_prescricao_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescricao',
            name='id',
        ),
        migrations.AddField(
            model_name='prescricao',
            name='Id',
            field=models.IntegerField(auto_created=True, default=3, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
